xcopy /C /Y ..\HidDisplay.XenoPlugins\bin\Debug\netstandard2.0\HidDisplay.XenoPlugins.deps.json .
xcopy /C /Y ..\HidDisplay.XenoPlugins\bin\Debug\netstandard2.0\HidDisplay.XenoPlugins.dll .
xcopy /C /Y ..\HidDisplay.XenoPlugins\bin\Debug\netstandard2.0\HidDisplay.XenoPlugins.pdb .
xcopy /C /Y ..\HidDisplay.DefaultConfigDataProviders\bin\Debug\netstandard2.0\HidDisplay.DefaultConfigDataProviders.deps.json .
xcopy /C /Y ..\HidDisplay.DefaultConfigDataProviders\bin\Debug\netstandard2.0\HidDisplay.DefaultConfigDataProviders.dll .
xcopy /C /Y ..\HidDisplay.DefaultConfigDataProviders\bin\Debug\netstandard2.0\HidDisplay.DefaultConfigDataProviders.pdb .
xcopy /C /Y ..\HidDisplay.DefaultPlugins\bin\Debug\netstandard2.0\HidDisplay.DefaultPlugins.deps.json .
xcopy /C /Y ..\HidDisplay.DefaultPlugins\bin\Debug\netstandard2.0\HidDisplay.DefaultPlugins.dll .
xcopy /C /Y ..\HidDisplay.DefaultPlugins\bin\Debug\netstandard2.0\HidDisplay.DefaultPlugins.pdb .